### ISSUE TITLE
DSM7.0で動作しない

### ISSUE THREAD

**Issue by ponzu07** [collelog/synology-make-px4_drv#1]
諸事情でDSMを6.2→7.0にアップデートしました。
対応していないので当たり前かもしれませんが、動作しません。
pkgscripts-ngが7.0に対応していないっぽい?
synology-make-px4_drvのDSM7.0対応は現状では厳しいですかね？
よろしくお願いします。

==========
$ ./EnvDeploy -v 7.0 --list
Available platforms:
==========

**Comment by collelog** [comment]
気付かず放置して申し訳ありません。
今更ではありますが4ヶ月前に重い腰を上げ、作りを変えて7.0に対応しています。
