### ISSUE TITLE
px4_drv.koが作成されない

### ISSUE THREAD

**Issue by PierreEmma** [collelog/synology-make-px4_drv#2]
久しぶりにDSMを更新したところ、以下のエラーになってしまいpx4_drv.koが作成されません。
DSM7.0~7.1まで3バージョンでそれぞれ試しましたが同様でした。
内部のコンポーネントかなにかが変わった影響でしょうか？

```
# docker run -it collelog/syno-make-px4_drv  /bin/bash
--------------------------------------------------
make px4_drv
--------------------------------------------------
gcc -O2 -Wall   -c -o fwtool.o fwtool.c
gcc -O2 -Wall   -c -o tsv.o tsv.c
gcc -O2 -Wall   -c -o crc32.o crc32.c
gcc -o fwtool fwtool.o tsv.o crc32.o
Archive:  pxw3u4_BDA_ver1x64.zip
Made with MacWinZipper (http://tidajapan.com/macwinzipper)
  inflating: PXW3U4.sys
fwtool for px4 drivers

Driver file (in)    : PXW3U4.sys
Firmware file (out) : it930x-firmware.bin

Driver description: PX-W3U4 BDA Ver.1.0 64bit
Firmware length: 2169 bytes
Firmware CRC32: 0b41a994
OK.
cp: cannot create directory '/build_env/usr/local/src/': No such file or directory
cp: cannot create directory '/build_env/usr/local/src/': No such file or directory
chroot: failed to run command '/bin/bash': No such file or directory
cp: cannot stat '/build_env/usr/local/src/driver/px4_drv.ko': No such file or directory
==================================================
completed builds.
 - /build_env/toolkit/results_file/px4_drv/px4_drv.ko
 - /build_env/toolkit/results_file/px4_drv/it930x-firmware.bin
==================================================
root@DS920:/volume1/docker/driver/px4_drv/driver#
```

DSM7.0の環境では直前のdocker run --rm --name syno-make-px4_drv -v [フルパス指定]:/build_env/toolkit/results_file/px4_drv -i -d collelog/syno-make-px4_drv　までは特にエラーなく行えました。
が、7.01xxx以上で実行すると
sudo docker build -t collelog/syno-make-px4_drv -f 7.0-geminilake.Dockerfile .
Sending build context to Docker daemon  86.02kB
Step 1/8 : FROM collelog/dsmpkg-env:7.0-geminilake as build_env
7.0-geminilake: Pulling from collelog/dsmpkg-env
Digest: sha256:753e6ddb2c11b64aacc25c7f98e2bd88b8ac22a815a30a680295067693143caf
Status: Downloaded newer image for collelog/dsmpkg-env:7.0-geminilake
 ---> f033524441c1
Step 2/8 : COPY syno_make_px4_drv.sh /toolkit/script/
 ---> 17f49faf58da
Step 3/8 : RUN chmod 755 /toolkit/script/syno_make_px4_drv.sh
 ---> Running in c12a3e7e946d
OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
のエラーで止まりました。

**Comment by collelog** [comment]
暫く放置し反応が遅れた事をお詫びします。
7.0-geminilake.Dockerfileのイメージビルド処理を見ると、syno_make_px4_drv.shの配置からchmodの直後で落ちているのでDockerのキャッシュが壊れてちゃんと動いていないかもしれません。
DSMのV7.01xとV7.0はツールチェインの変更が無いのでkoファイルはそのまま使用できます。
Dockerイメージやファイルも同じものを使用しますが、DSMのマイナーバージョンアップと共にDockerパッケージのバージョンアップも行われて、当時それが影響している可能性も考えられます。

今回DSM V7.1、V7.2用のDockerイメージとDockerファイルを用意しました。
まだ困っている場合はこちらをご使用してみてください。
